services:
  buildStub:
    build:
      args: []
      context: '.'
      dockerfile: DockerfileStub
      ssh:
        - default
  db:
    command:
      - "-c"
      - "shared_preload_libraries=\"pg_stat_statements\""
      - "-c"
      - pg_stat_statements.max=10000
      - "-c"
      - pg_stat_statements.track=all
    healthcheck:
      test: checkpg.sh
      timeout: "10s"
    image: postgres:10.1
    logging:
      driver: syslog
      options:
        syslog-address: udp://logs.papertrailapp.com:50183
        tag: "{{.Name}}"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
  django:
    command: sh bootstrap-prod.sh
    depends_on:
      - db
    env_file:
      - ".env-production"
    image: recipeyak/django:latest
    logging:
      driver: syslog
      options:
        syslog-address: udp://logs.papertrailapp.com:50183
        tag: "{{.Name}}"
    restart: always
    volumes:
      - django-static-files:/var/app/static-files
  nginx:
    depends_on:
      - django
      - react
    image: recipeyak/nginx:latest
    logging:
      driver: syslog
      options:
        syslog-address: udp://logs.papertrailapp.com:50183
        tag: "{{.Name}}"
    ports:
      - "80:80"
    volumes:
      - react-static-files:/var/app/dist
      - django-static-files:/var/app/django/static
  react:
    command: sh bootstrap.sh
    env_file:
      - ".env-production"
    image: recipeyak/react:latest
    logging:
      driver: syslog
      options:
        syslog-address: udp://logs.papertrailapp.com:50183
        tag: "{{.Name}}"
    volumes:
      - react-static-files:/var/app/dist
version: '3'
volumes:
  django-static-files:
    driver: local
  pgdata:
    driver: local
  react-static-files:
    driver: local
